### ISSUE TITLE
Bug with new version of corner

### ISSUE THREAD

**Issue by henedler** [JortBox/Halo-FDCA#14]
Hi, 
it seems like the newest version of the corner library (v2.2.1) introduces a bug somewhere. Using corner version 2.1.0, everything works. 

Here the Traceback:
```
Traceback (most recent call last):
  File "/home/p1uy068/opt/src/Halo-FDCA/FDCA/markov_chain_monte_carlo.py", line 768, in cornerplot
    fig = corner.corner(self.samples_units,labels=self.labels_units,truths=self.popt_units,
  File "/home/p1uy068/opt/lib/python3.8/site-packages/corner/corner.py", line 226, in corner
    return corner_impl(
  File "/home/p1uy068/opt/lib/python3.8/site-packages/corner/core.py", line 223, in corner_impl
    title = title.format(fmt(q_50), fmt(q_m), fmt(q_p))
ValueError: Invalid format specifier

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/p1uy068/opt/lib/python3.8/site-packages/corner/core.py", line 756, in _get_fig_axes
    return np.array(fig.axes).reshape((K, K))
ValueError: cannot reshape array of size 16 into shape (10,10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/p1uy068/opt/src/Halo-FDCA/HaloFitting.py", line 146, in <module>
    processing.plot_results()
  File "/home/p1uy068/opt/src/Halo-FDCA/FDCA/markov_chain_monte_carlo.py", line 639, in plot_results
    self.cornerplot()
  File "/home/p1uy068/opt/src/Halo-FDCA/FDCA/markov_chain_monte_carlo.py", line 771, in cornerplot
    fig = corner.corner(self.samples_units,labels=self.labels_units,truths=self.popt_units,
  File "/home/p1uy068/opt/lib/python3.8/site-packages/corner/corner.py", line 226, in corner
    return corner_impl(
  File "/home/p1uy068/opt/lib/python3.8/site-packages/corner/core.py", line 377, in corner_impl
    overplot_lines(fig, truths, color=truth_color)
  File "/home/p1uy068/opt/lib/python3.8/site-packages/corner/core.py", line 702, in overplot_lines
    axes = _get_fig_axes(fig, K)
  File "/home/p1uy068/opt/lib/python3.8/site-packages/corner/core.py", line 758, in _get_fig_axes
    raise ValueError(
ValueError: Provided figure has 16 axes, but data has dimensions K=10

```

**Comment by JortBox** [comment]
Updated the code to work with the newer version of corner
