### ISSUE TITLE
Fails when mask is specified

### ISSUE THREAD

**Issue by ktrehaeven** [JortBox/Halo-FDCA#15]
Good day

I've tried to run this command:
`HaloFitting.py Abell3444 AP.high_res.Deeper.predict.subtracted.Deeper.int.restored.image.conv15x15.mini_halo_2d_cutout.add_freq_axis.fits -z 0.254 -m_file high_res_contours.reg -spectr_idx -1.3 -model skewed -loc '10 23 50.1912 -27 15 22.503' -out_path skewed.convolved.rms.mask/ 2>&1 | tee A3444.convolved.rms.mask.log`

and get this error:
`Traceback (most recent call last):
  File "/home/trehaeven/halo-fdca_venv/bin/HaloFitting.py", line 124, in <module>
    outputpath=args.out_path, spectr_index=args.spectr_idx, rms=args.rms)
  File "/home/trehaeven/halo-fdca_venv/bin/FDCA/__init__.py", line 27, in Radio_Halo
    spectr_index=spectr_index, rms=rms)
  File "/home/trehaeven/halo-fdca_venv/bin/FDCA/HaloObject.py", line 115, in __init__
    self.image_mask, self.mask = utils.masking(self, mask)
  File "/home/trehaeven/halo-fdca_venv/bin/FDCA/fdca_utils.py", line 161, in masking
    mask_region(halo.path, regionpath, outfile)
  File "/home/trehaeven/halo-fdca_venv/bin/FDCA/fdca_utils.py", line 188, in mask_region
    hdu[0].data[0][0][np.where(manualmask == False)] = 0.0
TypeError: 'numpy.float32' object does not support item assignment`

The command runs fine when the mask is not specified.

Here is an overlay of the regions file on the image I'm trying to fit to:
![Screenshot from 2022-03-20 20-15-22](https://user-images.githubusercontent.com/77777044/159176593-da4e099c-cac6-4966-b872-037eca46f4c6.png)

The regions correspond to the point-like sources that were subtracted.

**Comment by ErikOsinga** [comment]
I have had this error as well. For me, it had to do with the fact that I was giving it .fits images with only 2 axes instead of 4. The code assumes that the fits images have 4 axes (i.e. 2 image plane RA,DEC and then FREQ and STOKES). 


I fixed this using the CASA function `importfits` and with settings `defaultaxes=True` and setting manually the `defaultaxesvalues`. 

I guess alternatively you can remove the `[0][0]` from the lines where it does `mask_region hdu[0].data[0][0]`, but I'm not sure how often that happens in the code.
